id: P001795
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 10:22:06.614710
source_metadata:
  id: bdr:W20230
  title: བོད་ཀྱི་ལ་གཞས་གཞོན་ནུ་འགུགས་པའི་ལྕགས་ཀྱུ
  author: ''
  volumes:
    78d58ae14bab455c9847a1b255d73b86:
      image_group_id: I4790
      title: ''
      volume_number: 1
      total_pages: 362
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
