id: I04440498
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T21:52:04+00:00'
last_modified: '2022-06-07T15:11:22.293664+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20230
  title: བོད་ཀྱི་ལ་གཞས་གཞོན་ནུ་འགུགས་པའི་ལྕགས་ཀྱུ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    A703:
      image_group_id: I4790
      title: ''
      total_pages: 362
      order: 1
      base_file: A703.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
